config/routes.rb
Pollapick::Application.routes.draw do
  devise_for :users, :controllers => {
             :omniauth_callbacks => 'omniauth_callbacks',
           }
  get "users/new"
  resources :polls do
    resources :rating_votes, only: [:create]
  end

  resources :options do
    member do
      put 'pick'
    end
  end

  root  'polls#index'
  get 'tags', to: 'polls#index', as: :tag
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :poll

	has_many :votes
  has_many :users, through: :votes

	def percentage
		@picks = []
		self.poll.options.each do |option|
			@picks << option.picks
		end

		@total_poll_picks = @picks.sum

		if @total_poll_picks == 0
			@percentage = 0
		else
			@percentage = ((self.picks.to_f) / (@total_poll_picks.to_f) * 100).round
		end
	
		@percentage
	end

	def pick_by user
		users_vote = votes.find_by(user_id: user.id)

		unless users_vote
			check_votes user.id

			self.picks += 1
			save

			votes.create(user_id: user.id)
		else
			self.picks -= 1
			save

			users_vote.destroy
		end

	end

	def check_votes user_id
		vote = poll.options.joins(:votes).map{ |option| option.votes.find_by(user_id: user_id) }.compact
		
		if vote.any?
			prev_option = vote.first.option
			prev_option.picks -= 1
			prev_option.save

			vote.first.destroy 
		end
	end
end

app/models/poll.rb
class Poll < ActiveRecord::Base
	has_many :options, dependent: :destroy
	has_many :rating_votes
  has_many :users, through: :rating_votes

	accepts_nested_attributes_for :options, :allow_destroy => true

  acts_as_taggable

  validates_presence_of :tag_list

	def total_poll_picks
		@picks = []
		self.options.each do |option|
			@picks << option.picks
		end
		
		@picks.sum 

	end

	def vote(direction, prev_vote = nil)
		if prev_vote.try(:up?)
			self.updownvote -= 1
      prev_vote.destroy
    elsif prev_vote.try(:down?)
    	self.updownvote += 1
    	prev_vote.destroy
    else
      direction == "up" ? self.updownvote += 1 : self.updownvote -= 1
		end
		
		save
	end
end

app/models/rating_vote.rb
class RatingVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :poll

  def up?
    direction == "up"
  end

  def down?
    direction == "down"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, 
         :recoverable, :rememberable, :trackable, :validatable, omniauth_providers: [:facebook, :twitter]

  has_many :votes
  has_many :options, through: :votes
  has_many :rating_votes
  has_many :polls, through: :rating_votes

  has_many :authorizations
  SOCIALS = {
    facebook: 'Facebook',
    twitter: "twitter"
  }

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, 
                                        :token => auth.credentials.token, 
                                        :secret => auth.credentials.secret).first_or_initialize
    authorization.profile_page = auth.info.urls.first.last unless authorization.persisted?
    if authorization.user.blank?
      user = current_user.nil? ? User.where('email = ?', auth['info']['email']).first : current_user
      if user.blank?
        user = User.new
        user.password = Devise.friendly_token[0, 20]
        user.fetch_details(auth)
        user.save
      end
      authorization.user = user
      authorization.save
    end
    authorization.user
  end

  def fetch_details(auth)
    self.name = auth.info.name
    self.email = auth.info.email
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :option
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path
    polls_path
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def all
    user = User.from_omniauth(env['omniauth.auth'], current_user)
    user.update_attributes(email: "#{user.name}_twitter@email.com") if env['omniauth.auth']['provider'] == "twitter"
    if user.persisted?
      sign_in user
      flash[:notice] = t('devise.omniauth_callbacks.success', :kind => User::SOCIALS[params[:action].to_sym])
      redirect_to root_path
      # if user.sign_in_count == 1
      #   redirect_to first_login_path
      # else
      # end
    else
      session['devise.user_attributes'] = user.attributes
      redirect_to new_user_registration_url
    end
  end

  User::SOCIALS.each do |k, _|
    alias_method k, :all
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  
  def pick
    @option = Option.find(params[:id])
    current_user ? @option.pick_by(current_user) : render(js: "window.location = #{new_user_session_path.to_json}")
  end
 end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :index
  # GET /polls
  def index
    @polls = params[:tag] ? Poll.tagged_with(params[:tag]).order(updownvote: :desc) : Poll.all.order(updownvote: :desc)

  end

  # GET /polls/1
  def show
    @poll = Poll.find(params[:id])
  end

  # GET /polls/new
  def new
    @poll = Poll.new
    @tags = ActsAsTaggableOn::Tag.all.pluck(:name).to_a
    2.times { @poll.options.build }
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  def create
    @poll = Poll.new(poll_params)
    if params[:add_option]
      @poll.options.build
      @tags = ActsAsTaggableOn::Tag.all.pluck(:name).to_a
    else
      @poll.save
      flash[:notice] = "Poll is public!"
      redirect_to poll_path(@poll) and return
    end
    render action: 'new'
  end

  # PATCH/PUT /polls/1
  def update
    if @poll.update(poll_params)
      redirect_to @poll, notice: 'Poll was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /polls/1
  def destroy
    @poll.destroy
    redirect_to polls_url, notice: 'Poll was successfully destroyed.'
  end

  def upvote
    @poll = Poll.find(params[:id])
    @poll.updownvote += 1
    @poll.save
    redirect_to polls_path

  end

  def downvote
    @poll = Poll.find(params[:id])
    @poll.updownvote -= 1
    @poll.save
    redirect_to polls_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def poll_params
      params.require(:poll).permit(:id, :question, :tag_list,
        options_attributes: [:id, :option_text, :percentage, :poll_id, :_destroy]
      )
    end
end

app/controllers/rating_votes_controller.rb
class RatingVotesController < ApplicationController
  before_action :check_user

  def create
    @poll = Poll.find(params[:poll_id])
    vote = @poll.rating_votes.find_by(user_id: current_user.id)

    if vote
      @poll.vote(params[:direction], vote)
    else
      RatingVote.create(poll_id: params[:poll_id], user_id: current_user.id, direction: params[:direction])
      @poll.vote(params[:direction])
    end    
  end

  private
  def check_user
    render(js: "window.location = #{new_user_session_path.to_json}") unless current_user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Pollapick"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/rating_votes_helper.rb
module RatingVotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
  <!-- Facebook -->
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        appId      : '1383455155310501',
        xfbml      : true,
        version    : 'v2.2'
      });
      $(document).trigger('fbload');
    };

    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
  </script>

  <!-- Twitter -->
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

  <!-- Pinterest -->
    <script type="text/javascript">
    (function(d){
        var f = d.getElementsByTagName('SCRIPT')[0], p = d.createElement('SCRIPT');
        p.type = 'text/javascript';
        p.async = true;
        p.src = '//assets.pinterest.com/js/pinit.js';
        f.parentNode.insertBefore(p, f);
    }(document));
  </script>


    <div class="navbar">
<!--       <% if current_user %>
        <%= current_user.name %>
      <% end %> -->
      <%= link_to "pollapick", root_path, class: "navbar-brand" %>
      <%= link_to 'New Poll', new_poll_path, :class => "btn-navbar" %>
<!--       <%= link_to 'Newest', polls_path, :sort => "newest", :class => "btn-navbar" %>
      <%= link_to 'Popular', root_path, :class => "btn-navbar" %> -->
      <%= current_user ? (link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn-navbar") : (link_to 'Sign In', new_user_session_path, class: "btn-navbar") %>

    </div>
    <br>
    <br>
    <br>  
    <%= yield %>

  </body>
</html>

app/views/options/pick.js.erb
$("#poll-<%= @option.poll.id %> .options-container").remove()
$('#poll-<%= @option.poll.id %> .poll-options').append("<%= j (render 'shared/options', poll: @option.poll) %>")
$('#option-<%= @option.id %> a').toggleClass("chosen")

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %> 

  <div class="form">
    <%= f.text_field :question, :class => 'form-field-question', :placeholder => "Type poll question here." %>   
    <%= f.fields_for :options do |ff| %>
        <%= ff.text_area :option_text, :class => 'form-field', :placeholder => "Type option here." %>           
        <br>
    <% end %>
    <%= f.submit '+ Option', :name => "add_option", :class => "btn-sm" %>
    <br>
    <br>
    <h3>Leave out hashtags--they're added automatically:</h3>
      <%= f.text_field :tag_list, :class => "tags-select", :placeholder => "Add tags here." %>
    </div>
    <br>
    <br>
  </div>
  <br>
  <%= f.submit nil, :class => "btn" %>
  <%= link_to 'Back', root_path, :class => "btn" %>

<% end %>

app/views/polls/edit.html.erb
<h2>Edit Poll</h2>

<%= render 'form' %>

app/views/polls/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<%= form_tag tag_path, method: :get do %>
  <h3>
  	Search by Tag:
  	<%= text_field_tag :tag, nil, :class => "form-field-search" %>
  	Update to polls index 2
  </h3>
<% end %>
<% @polls.each do |poll| %>
  <div class="poll-container poll-<%= poll.id %>">
    <%= render 'shared/poll', :poll => poll %>
  </div>
<% end %>

app/views/polls/new.html.erb
<h1>Create Your Poll</h1>

<%= render 'form' %>

<script type="text/javascript">
    $(".tags-select").select2({ tags: <%== @tags %>, selectOnBlur: true });
</script>

app/views/polls/show.html.erb
<h1>Viewing Poll:</h1>
<div class="poll-container poll-<%= @poll.id %>">
	<%= render 'shared/poll', :poll => @poll %>
</div>

<%= render "shared/social_buttons", poll: @poll %>

app/views/rating_votes/create.js.erb
$(".poll-<%= @poll.id %> .updownvote").remove()
$('.poll-<%= @poll.id %>').append("<%= j (render 'shared/poll_votes', poll: @poll) %>")

app/views/shared/_options.html.erb
<div class="options-container">
  <% poll.options.each do |option| %>
    <% if option.votes.where(user_id: current_user.try(:id)).any? %>
      <div class="option chosen" id="option-<%= option.id %>">
    <% else %>
      <div class="option" id="option-<%= option.id %>">
    <% end %>
        <%= link_to 'pick', pick_option_path(id: option.id), remote: true, method: :put, :class => "btn-pick" %>
        <div class="option-result">
          <%= option.option_text %>
          <br>
          <div class="progress">
            <div class="progress-bar" style="width: <%= option.percentage %>%;"><%= option.percentage %>%</div>
          </div>
        </div>
      </div>
  <% end %>
  <div class="poll-footer">
    &nbsp<br>
    <h3>
      Total Poll Picks: <%= poll.total_poll_picks %>&nbsp
      <% if controller_name == "polls" && action_name == "show" %>
        <%= link_to "Back to Polls", polls_path, :class => "btn-xs" %>
      <% else %>
        <%= link_to "View Poll", poll_path(poll), :class => "btn-xs" %>
      <% end %>
    </h3>
  </div>

</div>

app/views/shared/_poll.html.erb
<div class="poll" id="poll-<%= poll.id %>">
  <h2><%= poll.question %></h2>
  <div class="poll-options">
    <%= render "shared/options", poll: poll %>
  </div>
  <p><%= raw poll.tag_list.map { |t| link_to "##{t}", tag_path(tag: t), :class => "btn-tag" }.join(' ') %></p>
  <%= render("shared/social_buttons", poll: poll) if user_signed_in? %>
</div>

<%= render "shared/poll_votes", poll: poll %>

app/views/shared/_poll_votes.html.erb
<% if vote = poll.rating_votes.find_by(user_id: current_user.try(:id)) %>
  <div class="updownvote voted-<%= vote.direction %>">
<% else %>
  <div class="updownvote">
<% end %>
  <%= link_to "^", poll_rating_votes_path(poll.id, direction: "up"), method: :post, remote: true, :class => "btn-updownvote btn-updownvote-up" %>
  <br>
  <%= poll.updownvote %>
  <br>
  <%= link_to 'v', poll_rating_votes_path(poll.id, direction: "down"), method: :post, remote: true, :class => "btn-updownvote btn-updownvote-down" %>
</div>

app/views/shared/_social_buttons.html.erb
<a class="facebook" href="#" onclick="facebookShare()"><i class="fa fa-facebook-square"></i>Share</a>
<br>
<br>
<a href="https://twitter.com/share" class="twitter-share-button" data-via="twitter" data-count="none" data-url="<%= poll_url(poll) %>">Tweet</a>
<br>
<br>
<a href="https://www.pinterest.com/pin/create/button/
  ?url=<%= poll_url(poll) %>
  &description=Find out the answer and vote on PollaPick website!"
  data-pin-do="buttonPin"
  data-pin-config="above">
  <img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" />
</a>

<script type="text/javascript">
  function facebookShare(){
    FB.ui({
      method: 'feed',
      link: "<%= Rails.env == 'development' ? 'http://example.com/' : poll_url(poll) %>",
      name: "<%= poll.question %>",
      description: 'Find out the answer and vote on PollaPick website!',
    }, function(response){});
  }
</script>

app/views/shared/_social_buttons_feed.html.erb
<a class="facebook" href="#" onclick="facebookShare()"><i class="fa fa-facebook-square"></i>Share</a>
<br>
<br>
<a href="https://twitter.com/share" class="twitter-share-button" data-via="twitter" data-count="none">Tweet</a>
<br>
<br>
<a href="https://www.pinterest.com/pin/create/button/
  ?url=<%= root_url %>
  &description=Find out the answers and vote on PollaPick website!"
  data-pin-do="buttonPin"
  data-pin-config="above">
  <img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" />
</a>

<script type="text/javascript">
  function facebookShare(){
    FB.ui({
      method: 'feed',
      link: "<%= Rails.env == 'development' ? 'http://example.com/' : root_url %>",
      name: "PollaPick",
      description: 'Find out the answers and vote on PollaPick website!',
    }, function(response){});
  }
</script>

app/views/shared/_social_buttons_poll.html.erb
<a class="facebook" href="#" onclick="facebookShare()"><i class="fa fa-facebook-square"></i>Share</a>
<br>
<br>
<a href="https://twitter.com/share" class="twitter-share-button" data-via="twitter" data-count="none">Tweet</a>
<br>
<br>
<a href="https://www.pinterest.com/pin/create/button/
  ?url=<%= poll_url(@poll) %>
  &description=Find out the answer and vote on PollaPick website!"
  data-pin-do="buttonPin"
  data-pin-config="above">
  <img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" />
</a>

<script type="text/javascript">
  function facebookShare(){
    FB.ui({
      method: 'feed',
      link: "<%= Rails.env == 'development' ? 'http://example.com/' : poll_url(@poll) %>",
      name: "<%= @poll.question %>",
      description: 'Find out the answer and vote on PollaPick website!',
    }, function(response){});
  }
</script>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Pollapick') %>
<h1>About Pollapick</h1>
<p>
  Pollapick is in pre-alpha phase. Features are being developed. 
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>mikey<br> and<br> the<br> chickadee</h1>
  Here is where we will put some contact information when it exists. 
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help Me!</h1>
<p>
	This is probably where a FAQ page and other things will go. Maybe guidelines for posting and other stuff, too.
</p>

app/views/static_pages/home.html.erb
<h1>pollapick</h1>
	<hr>
	<h3>Make a new poll for people <br>to vote on (it's easy):</h3><br>
	<%= link_to "poll", new_poll_path, class: "btn btn-primary btn-lg" %><br><br>
	<hr>
	<h3>Cast your vote on other<br> people's polls (also easy):</h3><br>
	<%= link_to "pick", polls_path, class: "btn btn-primary btn-lg" %>